CREATE TABLE IF NOT EXISTS PRODUCT(
    ID TEXT,
    NAME TEXT,
    SUPPLIER_ID TEXT,
    CATEGORY TEXT,
    PRIZE REAL
);

INSERT INTO PRODUCT(ID, NAME, SUPPLIER_ID,CATEGORY,PRIZE) VALUES
    ('1','ME','2','BOX',100),
    ('22','I','21','WAX',900),
    ('13','U','22','WINK',100000000);

SELECT COUNT(ID) AS ID FROM PRODUCT;

SELECT AVG(PRIZE) AS AVGPRIZE FROM PRODUCT;

SELECT SUM(PRIZE) AS TOTAL FROM PRODUCT;